-- AULA 07 – ÁLGEBRA RELACIONAL EM SQL
-- Curso: Ciência da Computação
-- Banco de Dados II

SELECT PNOME, UNOME, ENDERECO
FROM FUNCIONARIO;

SELECT *
FROM FUNCIONARIO
WHERE DNR = 4;

SELECT *
FROM FUNCIONARIO
WHERE (DNR = 4 AND SALARIO > 25000)
    OR (DNR = 5 AND SALARIO > 30000);

SELECT PNOME, UNOME, SALARIO
FROM FUNCIONARIO
WHERE DNR = 5;

SELECT PNOME AS NOME, UNOME AS SOBRENOME, SALARIO
FROM FUNCIONARIO
WHERE DNR = 5;

SELECT CPF
FROM FUNCIONARIO
WHERE DNR = 5
UNION
SELECT CPF_SUPERVISOR
FROM FUNCIONARIO
WHERE DNR = 5;

SELECT CPF
FROM FUNCIONARIO
WHERE DNR = 5
INTERSECT
SELECT CPF_SUPERVISOR
FROM FUNCIONARIO
WHERE DNR = 5;

SELECT CPF
FROM FUNCIONARIO
EXCEPT
SELECT CPF_SUPERVISOR
FROM FUNCIONARIO;

SELECT *
FROM FUNCIONARIO, DEPARTAMENTO;

SELECT F.PNOME, F.UNOME, D.NOMEDEPENDENTE
FROM FUNCIONARIO AS F, DEPENDENTE AS D
WHERE F.SEXO = 'F' AND F.CPF = D.FCPF;

SELECT D.DNOME, F.PNOME, F.UNOME
FROM DEPARTAMENTO AS D
JOIN FUNCIONARIO AS F
ON D.CPF_GERENTE = F.CPF;

CREATE TABLE ALUNO (
    cod_aluno INT PRIMARY KEY,
    nome VARCHAR(100),
    matricula VARCHAR(20),
    telefone VARCHAR(15),
    cpf VARCHAR(14),
    coeficiente NUMERIC(3,2)
);

CREATE TABLE FUNCIONARIO (
    cod_prof INT PRIMARY KEY,
    nome VARCHAR(100),
    matricula VARCHAR(20),
    telefone VARCHAR(15),
    cpf VARCHAR(14),
    cod_cargo INT
);

CREATE TABLE CARGO (
    cod_cargo INT PRIMARY KEY,
    dcr_cargo VARCHAR(50)
);

CREATE TABLE TURMA (
    cod_turma INT PRIMARY KEY,
    dcr_turma VARCHAR(50),
    cod_professor INT,
    cod_disciplina INT
);

CREATE TABLE ALUNO_TURMA (
    cod_turma INT,
    cod_aluno INT,
    nota NUMERIC(4,2),
    freq NUMERIC(5,2),
    PRIMARY KEY (cod_turma, cod_aluno)
);

CREATE TABLE DISCIPLINA (
    cod_disciplina INT PRIMARY KEY,
    dcr_disciplina VARCHAR(100)
);

CREATE TABLE PREREQUISITO (
    cod_disc_pre INT,
    cod_disc_pos INT,
    PRIMARY KEY (cod_disc_pre, cod_disc_pos)
);

INSERT INTO CARGO (cod_cargo, dcr_cargo) VALUES
(1, 'Professor'),
(2, 'Funcionario');

SELECT A.nome, AT.nota
FROM ALUNO A
JOIN ALUNO_TURMA AT ON A.cod_aluno = AT.cod_aluno;

SELECT T.dcr_turma, F.nome AS professor
FROM TURMA T
JOIN FUNCIONARIO F ON T.cod_professor = F.cod_prof;

SELECT D1.dcr_disciplina AS Disciplina, D2.dcr_disciplina AS Pre_Requisito
FROM DISCIPLINA D1
JOIN PREREQUISITO P ON D1.cod_disciplina = P.cod_disc_pos
JOIN DISCIPLINA D2 ON D2.cod_disciplina = P.cod_disc_pre;
