-- AULA 11 – CONSULTAS ANINHADAS, JOINS E FUNÇÕES AGREGADAS
-- Banco de Dados II
-- Curso: Ciência da Computação

SELECT PNOME, UNOME, ENDERECO
FROM FUNCIONARIO
WHERE DEPARTAMENTO_DNUMERO IN (
    SELECT DNUMERO
    FROM DEPARTAMENTO
    WHERE DNOME = 'Pesquisa'
);

SELECT F.PNOME, F.UNOME
FROM FUNCIONARIO AS F
WHERE F.CPF IN (
    SELECT FUNCIONARIO_CPF
    FROM DEPENDENTE
    WHERE FUNCIONARIO_CPF = F.CPF
        AND F.PNOME = NOMEDEPENDENTE
);

SELECT F.PNOME, F.UNOME
FROM FUNCIONARIO AS F
JOIN DEPENDENTE AS D
    ON F.CPF = D.FUNCIONARIO_CPF
WHERE F.PNOME = D.NOMEDEPENDENTE;

SELECT F.PNOME, F.UNOME
FROM FUNCIONARIO AS F
WHERE EXISTS (
    SELECT * FROM DEPENDENTE
    WHERE FUNCIONARIO_CPF = F.CPF
        AND F.PNOME = NOMEDEPENDENTE
);

SELECT PNOME, UNOME
FROM FUNCIONARIO
WHERE NOT EXISTS (
    SELECT * FROM DEPENDENTE
    WHERE CPF = FUNCIONARIO_CPF
);

SELECT PNOME, UNOME
FROM FUNCIONARIO
WHERE EXISTS (
    SELECT * FROM DEPENDENTE
    WHERE CPF = FCPF
)
AND EXISTS (
    SELECT * FROM DEPARTAMENTO
    WHERE CPF = CPF_SUPERVISOR
);

SELECT DISTINCT FUNCIONARIO_CPF
FROM TRABALHA_EM
WHERE PROJETO_PROJNUMERO IN (1, 2, 3);

SELECT CPF, DNOME
FROM FUNCIONARIO CROSS JOIN DEPARTAMENTO;

SELECT f.PNOME, f.UNOME, f.ENDERECO
FROM FUNCIONARIO AS f
INNER JOIN DEPARTAMENTO AS d
    ON f.DEPARTAMENTO_DNUMERO = d.DNUMERO
WHERE d.DNOME = 'Pesquisa';

SELECT F.PNOME AS FUNCIONARIO, F.UNOME AS SOBRENOME,
        S.PNOME AS SUPERVISOR, S.UNOME AS SOBRENOME_SUP
FROM FUNCIONARIO AS F
LEFT OUTER JOIN FUNCIONARIO AS S
    ON F.SUPERVISOR_CPF = S.CPF;

SELECT *
FROM TABELA1
RIGHT OUTER JOIN TABELA2
    ON TABELA1.COD = TABELA2.COD;

SELECT *
FROM TABELA1
FULL OUTER JOIN TABELA2
    ON TABELA1.COD = TABELA2.COD;

SELECT DNOME, DLOCALIZACAO
FROM DEPARTAMENTO
NATURAL JOIN LOCAIS_DEPTO
WHERE DNOME = 'Pesquisa';

SELECT COUNT(*) AS TOTAL_FUNCIONARIOS
FROM FUNCIONARIO;

SELECT COUNT(DISTINCT SALARIO) AS SALARIOS_DIFERENTES
FROM FUNCIONARIO;

SELECT SUM(SALARIO) AS TOTAL_SALARIOS
FROM FUNCIONARIO;

SELECT MAX(SALARIO) AS MAIOR_SALARIO
FROM FUNCIONARIO;

SELECT MIN(SALARIO) AS MENOR_SALARIO_PESQUISA
FROM FUNCIONARIO
JOIN DEPARTAMENTO ON DNO = DNUMERO
WHERE DNOME = 'Pesquisa';

SELECT AVG(SALARIO) AS MEDIA_SALARIO
FROM FUNCIONARIO;

SELECT PNOME, UNOME
FROM FUNCIONARIO
WHERE (
    SELECT COUNT(*)
    FROM DEPENDENTE
    WHERE CPF = FCPF
) >= 2;

SELECT DNO, COUNT(*) AS QTD_FUNCIONARIOS, AVG(SALARIO) AS MEDIA_SALARIAL
FROM FUNCIONARIO
GROUP BY DNO;

SELECT PNUMERO, PJNOME, COUNT(*) AS QTD_FUNCIONARIOS
FROM PROJETO, TRABALHA_EM
WHERE PNUMERO = PNO
GROUP BY PNUMERO, PJNOME
HAVING COUNT(*) > 2;
